runtime: python39
handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /about
  static_files: public/about.html
  upload: public/about.html

- url: /contact
  static_files: public/contact.html
  upload: public/contact.html
